In [ ]:
import pandas as pd
import datetime
import glob
import json
import matplotlib.pyplot as plt
import numpy as np
import bokeh
from scipy import stats

In [ ]:
#CSV selektieren

#OHNE Batterie:
#files = (glob.glob("data/data1/*.csv"))


#MIT Batterie:
files = (glob.glob("data/data2/*.csv"))

for file in files:
    print(file)

In [109]:
#csv einlesen in df
df = None
for file in files:
    
    if df is None:
        df=pd.read_csv(file, error_bad_lines=False, low_memory=False, sep=";", decimal=",")
       # df.index = pd.to_datetime(df.index)
       # df
    
    else:
        df=df.append(pd.read_csv(file, error_bad_lines=False, low_memory=False, sep=";", decimal=","))
        #df.index = pd.to_datetime(df.index)
       

df.head(30)

,DateTime,DevWork_97 [Energy_Ws],FromBattToConsumer_0 [Energy_Wh],FromGenToBatt_0 [Energy_Wh],FromGenToConsumer_0 [Energy_Wh],FromGenToGrid_0 [Energy_Wh],FromGridToConsumer_0 [Energy_Wh],FromGrid_0 [Energy_Wh],StateOfCharge_254 [Percent],ToConsumer_0 [Energy_Wh]
0,2017-01-01 00:05:00+01:00,0.0,0.0,0.0,0.0,0.0,49.87,50.0,7.0,49.87
1,2017-01-01 00:10:00+01:00,0.0,0.0,0.0,0.0,0.0,45.93,46.0,7.0,45.93
2,2017-01-01 00:15:00+01:00,0.0,0.0,0.0,0.0,0.0,42.81,43.0,7.0,42.81
3,2017-01-01 00:20:00+01:00,0.0,0.0,0.0,0.0,0.0,41.85,42.0,7.0,41.85
4,2017-01-01 00:25:00+01:00,0.0,0.0,0.0,0.0,0.0,44.85,45.0,7.0,44.85
5,2017-01-01 00:30:00+01:00,0.0,0.0,0.0,0.0,0.0,43.00,43.0,7.0,43.00
6,2017-01-01 00:35:00+01:00,0.0,0.0,0.0,0.0,0.0,46.87,47.0,7.0,46.87
7,2017-01-01 00:40:00+01:00,0.0,0.0,0.0,0.0,0.0,44.90,45.0,7.0,44.90
8,2017-01-01 00:45:00+01:00,0.0,0.0,0.0,0.0,0.0,46.91,47.0,7.0,46.91
9,2017-01-01 00:50:00+01:00,0.0,0.0,0.0,0.0,0.0,45.90,46.0,7.0,45.90
10,2017-01-01 00:55:00+01:00,0.0,0.0,0.0,0.0,0.0,53.87,54.0,7.0,53.87
11,2017-01-01 01:00:00+01:00,0.0,0.0,0.0,0.0,0.0,53.00,53.0,7.0,53.00
12,2017-01-01 01:05:00+01:00,0.0,0.0,0.0,0.0,0.0,50.85,51.0,7.0,50.85
13,2017-01-01 01:10:00+01:00,0.0,0.0,0.0,0.0,0.0,47.89,48.0,7.0,47.89
14,2017-01-01 01:15:00+01:00,0.0,0.0,0.0,0.0,0.0,39.92,40.0,7.0,39.92
15,2017-01-01 01:20:00+01:00,0.0,0.0,0.0,0.0,0.0,52.84,53.0,7.0,52.84
16,2017-01-01 01:25:00+01:00,0.0,0.0,0.0,0.0,0.0,37.94,38.0,7.0,37.94
17,2017-01-01 01:30:00+01:00,0.0,0.0,0.0,0.0,0.0,35.82,36.0,7.0,35.82
18,2017-01-01 01:35:00+01:00,0.0,0.0,0.0,0.0,0.0,32.97,33.0,7.0,32.97
19,2017-01-01 01:40:00+01:00,0.0,0.0,0.0,0.0,0.0,29.87,30.0,7.0,29.87
20,2017-01-01 01:45:00+01:00,0.0,0.0,0.0,0.0,0.0,36.94,37.0,7.0,36.94
21,2017-01-01 01:50:00+01:00,0.0,0.0,0.0,0.0,0.0,33.91,34.0,7.0,33.91
22,2017-01-01 01:55:00+01:00,0.0,0.0,0.0,0.0,0.0,34.87,35.0,7.0,34.87
23,2017-01-01 02:00:00+01:00,0.0,0.0,0.0,0.0,0.0,27.90,28.0,7.0,27.90
24,2017-01-01 02:05:00+01:00,0.0,0.0,0.0,0.0,0.0,29.81,30.0,7.0,29.81
25,2017-01-01 02:10:00+01:00,0.0,0.0,0.0,0.0,0.0,27.00,27.0,7.0,27.00
26,2017-01-01 02:15:00+01:00,0.0,0.0,0.0,0.0,0.0,28.76,29.0,7.0,28.76
27,2017-01-01 02:20:00+01:00,0.0,0.0,0.0,0.0,0.0,36.78,37.0,7.0,36.78
28,2017-01-01 02:25:00+01:00,0.0,0.0,0.0,0.0,0.0,28.79,29.0,7.0,28.79
29,2017-01-01 02:30:00+01:00,0.0,0.0,0.0,0.0,0.0,32.82,33.0,7.0,32.82

In [110]:
#ALLE Daten in einem File speichern:
#df.to_csv('alle_Anlagen_ohne_Bat', index = False)

# math. Formel zur Erzeugung des Profils:

In [111]:
df2=df
df2.shape #kontrolle

(10086737, 10)

In [112]:
#Synthetisch DURCHSCHNITT
#df2 = df.groupby(df.DateTime ,as_index=True).mean().round(2).reset_index()

#Synthetisch MEDIAN
#df2 = df2.groupby(df2.DateTime ,as_index=True).median().round(2).reset_index()

#Aggregieren mit getrimmmten Mean
df2=df2.groupby("DateTime").agg(lambda x: stats.trim_mean(x, 0.25)).round(2).reset_index()

In [113]:
df2.shape

(438552, 10)

In [114]:
#df2.isna()

In [115]:
#Analyse mit Pandas Profiling
#from pandas_profiling import ProfileReport

#profile = ProfileReport(df2, title="Pandas Profiling Report  Synthetisches LP ohne Batterie")

In [116]:
#profile

In [117]:
#profile.to_file("profile_all_mit_bat.html")

In [118]:
df2.head()

,DateTime,DevWork_97 [Energy_Ws],FromBattToConsumer_0 [Energy_Wh],FromGenToBatt_0 [Energy_Wh],FromGenToConsumer_0 [Energy_Wh],FromGenToGrid_0 [Energy_Wh],FromGridToConsumer_0 [Energy_Wh],FromGrid_0 [Energy_Wh],StateOfCharge_254 [Percent],ToConsumer_0 [Energy_Wh]
0,2017-01-01 00:05:00+01:00,0.0,0.0,0.0,0.0,0.0,31.53,31.54,NaN,35.33
1,2017-01-01 00:10:00+01:00,0.0,0.0,0.0,0.0,0.0,33.46,33.46,NaN,37.96
2,2017-01-01 00:15:00+01:00,0.0,0.0,0.0,0.0,0.0,35.67,35.69,NaN,38.08
3,2017-01-01 00:20:00+01:00,0.0,0.0,0.0,0.0,0.0,33.68,33.69,NaN,35.73
4,2017-01-01 00:25:00+01:00,0.0,0.0,0.0,0.0,0.0,29.92,30.00,NaN,32.33

In [119]:
df2['DateTime'] =  pd.to_datetime(df2['DateTime'], format="%Y-%m-%d", utc=True) #umwandeln in DateTime Format läuft

In [120]:
#df2.dtypes #kontrolle ob datetime anstatt object

In [121]:
df2['DateTime']=df2['DateTime'].dt.tz_convert('Europe/Berlin') #umwandeln von utc auf CET

In [122]:
#df2.head()

In [123]:
df2.dtypes

DateTime                            datetime64[ns, Europe/Berlin]
DevWork_97 [Energy_Ws]                                    float64
FromBattToConsumer_0 [Energy_Wh]                          float64
FromGenToBatt_0 [Energy_Wh]                               float64
FromGenToConsumer_0 [Energy_Wh]                           float64
FromGenToGrid_0 [Energy_Wh]                               float64
FromGridToConsumer_0 [Energy_Wh]                          float64
FromGrid_0 [Energy_Wh]                                    float64
StateOfCharge_254 [Percent]                               float64
ToConsumer_0 [Energy_Wh]                                  float64
dtype: object

In [124]:
df2.to_csv('Data/data3/synt_mit_bat_mittelwert_trimmed.csv', index = False, sep = ';')

In [125]:
 #df.groupby(pd.Grouper(freq='M')